// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWMMTApfGmIwDmk2JnvE0lwOTG0MoKNY',
    appId: '1:860150173112:web:03dd760a1692221ebdd34d',
    messagingSenderId: '860150173112',
    projectId: 'travel-motto',
    authDomain: 'travel-motto.firebaseapp.com',
    storageBucket: 'travel-motto.appspot.com',
    measurementId: 'G-5SNXRPH0PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbBxMSqpIbFTYuhjAuLsF3Un9iIsKPvoM',
    appId: '1:860150173112:android:5609c3122243e7e9bdd34d',
    messagingSenderId: '860150173112',
    projectId: 'travel-motto',
    storageBucket: 'travel-motto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNmqeEWjwpjhmH3Hcfg0XURhyX_AXlrM',
    appId: '1:860150173112:ios:a7b39e02b1a00a43bdd34d',
    messagingSenderId: '860150173112',
    projectId: 'travel-motto',
    storageBucket: 'travel-motto.appspot.com',
    iosBundleId: 'com.example.travelMotto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNmqeEWjwpjhmH3Hcfg0XURhyX_AXlrM',
    appId: '1:860150173112:ios:f1a85f9edd477993bdd34d',
    messagingSenderId: '860150173112',
    projectId: 'travel-motto',
    storageBucket: 'travel-motto.appspot.com',
    iosBundleId: 'com.example.travelMotto.RunnerTests',
  );
}
